[package]
name = "elias_fano_rust"
version = "0.1.0"
authors = ["zom <tommaso.fontana.96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec_rand = { git = "https://github.com/zommiommy/vec_rand", branch = "master" }
rsdict = { git = "https://github.com/zommiommy/rsdict/", branch="patch-1", features= ["simd"] }
rayon = "1.1"

[dev-dependencies]
rand = {version="0.7", features = ["small_rng"] }